### ISSUE TITLE
systemd: Can't bind vault to port 443

### ISSUE THREAD

**Issue by fhemberger** [ansible-community/ansible-vault#107]
I try to run vault on port 443 (using default user/group), however, I get the following error:

```
error initializing listener of type tcp: listen tcp xx.xx.xx.xx:443: bind: permission denied
```

I tried adding CAP_NET_BIND_SERVICE to both `CapabilityBoundingSet` and `AmbientCapabilities`, but that still didn't work for me. Any ideas?

**Comment by brianshumate** [comment]
Hi!

This is more a systemd and Linux administration question than a Vault specific question, but I can offer a couple ideas:

1. Don't attempt what you are attempting; Vault runs on TCP/8200 by default, which is an unprivileged port that can be bound to by a non-root user. Most users requiring access to Vault on another port use a network service like a proxy to achieve this instead of binding Vault to an unconventional port.
2. If you must have Vault running on port 443 and do not want to follow best practices, then you could look into adding the capability on the `vault` binary itself with something like:

```
sudo setcap cap_net_bind_service=+ep /path/to/vault
```

**Note that this change lets _any user_ start `vault` and bind to _any port_, which is certainly not the most secure solution**.

Since this question doesn't really relate to Vault itself or this role, I am also closing it.

Best of luck!

**Comment by v0ctor** [comment]
Considering that it is not a good practice to change the default port and that adding the `NET_BIND_SERVICE` capability has security implications, a good solution could be to forward the port with iptables:

```Shell
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8200
```

With Ansible:

```yaml
- ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: 443
    jump: REDIRECT
    to_ports: 8200
```

It may not be elegant, but it is a secure way to serve the Vault UI over the standard HTTP (over TLS) port.

**Comment by alloran** [comment]
Any capabilities set on the filesystem level disable ambient capabilities set by systemd.
Vault binary in rpm\deb packages is shipped with cap_ipc_lock
```
$ getcap $(which vault) 
/usr/bin/vault = cap_ipc_lock+ep
```

So just remove all capabilities before starting vault.
```
cat /etc/systemd/system/vault.service.d/override.conf 
[Service]
ExecStartPre=+/usr/sbin/setcap -r /usr/bin/vault
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_IPC_LOCK
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_SYSLOG CAP_IPC_LOCK

```
